encrypt:
  key: obk-msa-pro-key

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  cloud:
    bus:
      enabled: true
      destination: msa-bus-topic
    stream:
      kafka:
        binder:
          brokers: localhost:29092
  kafka:
    bootstrap-servers: localhost:29092
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

user-service: 
  url: http://USERMICROSERVICE/user-service

product-service: 
  url: http://PRODUCTMICROSERVICE/product-service

order-service: 
  url: http://ORDERMICROSERVICE/order-service

notification-service: 
  url: http://NOTIFICATIONMICROSERVICE/notification-service

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  observation:
    key-values:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*" # 추적 현황 확인을 위해 전체 노출 권장
      
welcome:
  message: This is micro ${spring.application.name}

  
