encrypt:
  key: obk-msa-pro-key

spring:
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: '{cipher}b879342222bd5b0d33641c640526196977114bedad733236d34bd018a18fe250'
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

user-service: 
  url: http://USERMICROSERVICE/user-service

product-service: 
  url: http://PRODUCTMICROSERVICE/product-service

order-service: 
  url: http://ORDERMICROSERVICE/order-service

notification-service: 
  url: http://NOTIFICATIONMICROSERVICE/notification-service

management:
  tracing:
    sampling:
      probability: 1.0  # 추적 데이터 수집 비율 (1.0 = 100%)
  zipkin:
    tracing:
      endpoint: "http://your-zipkin-server:9411/api/v2/spans"
  observations:
    key-values:
      application: ${spring.application.name} # Zipkin에서 서비스명 식별용
      
welcome:
  message: This is micro ${spring.application.name}

  
